---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.2.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
          - "--profile=production"

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: .github/.*
        files: \.(yaml|yml)$
        types: [file, yaml]
        always_run: true
        entry: yamllint --strict .

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        exclude: .github/.*

  - repo: https://github.com/errata-ai/vale.git
    rev: v3.4.1
    hooks:
      - id: vale
        exclude: .github/.*
        files: \.(md)$
...
