---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.7.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
          - "--profile=production"

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: .github/.*
        files: \.(yaml|yml)$
        types: [file, yaml]
        always_run: true
        entry: yamllint --strict .

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        exclude: .github/.*

  - repo: https://github.com/errata-ai/vale.git
    rev: v3.12.0
    hooks:
      - id: vale
        exclude: .github/.*
        files: \.(md)$
...
