---
namespace: rhjhunt
name: containerized_aap_analytics
version: 1.0.0
readme: README.md
authors:
  - Jacob Hunt (https://github.com/rhjhunt)
description: Collection to install containerized Grafana and Prometheus for Automation Analytics
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags:
  - containers
  - podman
  - aap
  - metrics
  - controller
  - monitoring
dependencies:
  containers.podman: "*"
  grafana.grafana: "*"
  ansible.posix: "*"
repository: https://github.com/rhjhunt/containerized_aap_analytics
documentation: https://github.com/rhjhunt/containerized_aap_analytics
homepage: https://github.com/rhjhunt/containerized_aap_analytics
issues: https://github.com/rhjhunt/containerized_aap_analytics/issues
build_ignore:
  - .vale.ini
  - .yamllint
  - .markdownlint.yml
  - .github
  - .gitignore
  - "*.tar.gz"
  - venv/
  - molecule/
  - requirements.txt
