---
- name: Ensure grafana admin password is provided
  ansible.builtin.assert:
    that:
      - grafana_admin_password is defined
      - grafana_admin_password | length
    fail_msg: grafana_admin_password must be set and not empty
  when: groups.get('grafana', []) | length > 0
...
