---
name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.4

      - name: Setup Python
        uses: actions/setup-python@v5.1.0

      - name: Run pre-commit
        uses: pre-commit/actions@v3.0.1
...
